---
title: "Publications"
output: 
  html_document: 
    toc: no
---


## Refereed Journal Articles

2021 "Impacts of the FLEGT Action Plan and the EU Timber Regulation on EU Trade in Timber Product".
Paul Rougieux and Ragnar Jonsson.
Sustainability 2021, 13(11), 6030; https://doi.org/10.3390/su13116030
([R code and data](https://gitlab.com/paulrougieux/eutr_trade_impact_sustainability/))

2021 "Comparing Reported Forest Biomass Gains and Losses in European and Global Datasets".
Lucas Sinclair and Paul Rougieux.
Forests 2021, 12(2), 176; https://doi.org/10.3390/f12020176 
([python code](https://github.com/xapple/forest_puller) and [data](https://github.com/xapple/puller_cache))

2018: "Reassessing forest products demand functions in Europe using a panel co-integration approach".
Paul Rougieux and Olivier Damette.
Applied Economics, Pages 3247-3270 | Published online: 03 Jan 2018;
https://doi.org/10.1080/00036846.2017.1420887
([data](data/data_Reassessing_forest_products_demand_functions_in_Europe_using_a_panel_cointegration_approach.zip)).

2014: "Potential impact of a Transatlantic Trade and Investment Partnership on the global forest sector".
Joseph Buongiorno, Paul Rougieux, Ahmed Barkaoui, Shushuai Zhu and Patrice Harou.
Journal of Forest Economics, Vol 20, No 3, 252-266;
https://doi.org/10.1016/j.jfe.2014.07.001
([R code to read GFPM output data](https://github.com/paulrougieux/GFPMoutput))


## Technical reports and other publications

2017: "The Forest Products Trade Flow Database – A reproducible method and tool to support the analysis of international forest products trade", 
with Jo Van Brusselen, Marko Lovrić, Janne Kiljunen, Simo Varis and Sergey Zudin,
[EFI Technical Report No 100](https://efi.int/publications-bank/forest-products-trade-flow-database-reproducible-method-and-tool-support-analysis),
([pdf](https://efi.int/sites/default/files/files/publication-bank/2018/tr_100.pdf))
([R code](https://github.com/EuropeanForestInstitute/tradeflows))


## PhD Thesis

2017: "Modelling European Forest Products Consumption and Trade in a Context of Structural Change"
defended on 09-03-2017 in Université de Lorraine, https://www.theses.fr/en/2017LORR0004


