

# Academic editing

## Conjunctions

### Linking words

Example [50 linking words to use in academic 
writting](https://www.eliteediting.com.au/50-linking-words-to-use-in-academic-writing/)

> **Describing similarities**: likewise, correspondingly, equally, not only…
> but also, in the same way, similarly

> **Showing cause and effect**: consequently, as a result, thus, hence (never
> ‘hence why’), since (try to avoid ‘as’ when showing cause and effect),
> because, therefore, accordingly, this suggests that, it follows that, for
> this reason 

> **Comparing and contrasting**: alternatively, however, conversely, on the
> other hand, instead, yet, on the contrary

> **Showing limitation or contradiction**: despite/in spite of, while (not
> whilst!), even so, on the contrary, nevertheless, nonetheless, although,
> admittedly 

> **Emphasis, addition or examples**: to illustrate, to clarify, further (not
> ‘furthermore’), first, second and third (not firstly, secondly and thirdly),
> for instance, moreover, typically, especially, in fact, namely, in addition

> **Concluding**: to summarise, it can be concluded that, as can be seen,
> ultimately, given the above, as described, finally

Blog explanation from Grammarly [on the use of
firstly](https://www.grammarly.com/blog/firstly/)

> It is not wrong to use firstly, secondly, and so on to enumerate your points.
> Nor is it wrong to use the simpler first, second, etc. 

> I have three reasons for wanting to visit Rome. Firstly, I would love to see
> the Colosseum. Secondly, I’m sure the pope is dying to meet me. Thirdly, they
> have great pizza. 

> I have three reasons for wanting to visit Rome. First, I would love to see
> the Colosseum. Second, I’m sure the pope is dying to meet me. Third, I need
> better pizza. 

> "These statements are equivalent in meaning. Nevertheless, there are good
> reasons for choosing the “first” sequence over the “firstly” sequence. First,
> using first is a sure win. If your writing is being published or evaluated,
> or even if you would like to seem proficient to your coworkers, use the
> construction that is never criticized rather than the one that is frequently
> criticized."


### Coordinating conjunctions

academicguides.waldenu.edu 
[conjunctions](https://academicguides.waldenu.edu/writingcenter/grammar/conjunctions)

> "Coordinating conjunctions connect words or phrases that serve the same grammatical purpose in a sentence. There are seven main coordinating conjunctions in English, which form the acronym FANBOYS:

> F: for: The teachers were frustrated, for the school had cut funding for all 
>    enrichment programs.

> A: and: In this course, I will write a literature review, a case study, and a final 
>    paper.

> N: nor: The students did not complete their homework, nor did they pass the test.

> B: but: The study is several years old but still valuable to this study.

> O: or: At the end of the class, the students can choose to write an essay or take a test.

> Y: yet: The patient complained of chronic pain, yet she refused treatment.

> S: so: I have only been a nurse for one year, so I have little experience with paper 
     charting.*


### Subordinating conjunctions

academicguides.waldenu.edu 
[conjunctions](https://academicguides.waldenu.edu/writingcenter/grammar/conjunctions)

Subordinating conjunctions join a subordinate clause to a main clause and establishes a relationship between the two. There are many subordinating clauses, but here are some of the most common:

    after, although, as much as/as soon as/as long as, as though, because, before, how, 
    if, in order to/in order that, once, since, than, that, though, unless, until, 
    when/whenever, where/wherever, whether, while


### That as a conjunction for noun clauses

academicguides.waldenu.edu 
[conjunctions](https://academicguides.waldenu.edu/writingcenter/grammar/conjunctions)

> "For example,
>
>    Smith (2015) reported that more research was necessary.
>        Smith (2015) = subject
>        reported = verb
>        that more research was necessary = dependent clause, direct object of the verb "reported"
>    The authors hypothesized that there would be significant results.
>        The authors = subject
>        hypothesized = verb
>        that there would be significant results = dependent clause, direct object of the verb "hypothesized"
>    Jones (2014) asserted that confidentiality was maintained throughout the study.
>        Jones (2014) = subject
>        asserted = verb
>        that confidentiality was maintained throughout the study = dependent clause, direct object of the verb "asserted"
>    Rephrasing these sentences into questions and answers is one way to see that the "that" clauses are acting as direct objects.
>        What did Smith (2015) report?
>            Answer: that more research was necessary
>        What did the authors hypothesize?
>            Answer: that there would be significant results
>        What did Jones (2014) assert?
>            Answer: that confidentiality was maintained throughout the study
>
> In formal written English, for clarity, most academic writers choose to keep "that" 
> when it introduces a noun clause (Caplan, 2012). Leaving out "that" can cause the 
> reader to misread (at first anyway) the subject of the dependent clause as being the 
> object of the reporting verb (Jamieson, 2012).
>
> For example, if readers see the sentence, "Smith (2015) reported more research was 
> necessary (without 'that')," they may understand “more research” as the thing Smith 
> reported and then have to backtrack and reread upon seeing “was necessary.”
> Any structure that leads to misinterpretation, even temporarily, can be an unwanted 
> distraction from the writer’s message.
> In spoken English, however, "that" may be dropped in such sentences. (Intonation 
> patterns—rising and falling pitch—give the listener clues that may not be present in 
> writing.)"


## Verbs


editage.com [impressive verbs to use in your research 
paper](https://www.editage.com/all-about-publication/research/impressive-Verbs-to-use-in-your-Research-Paper.html)

| Purpose                                                        | Verbs                                                                                         |  
| :------------------------------------------------------------: | :-------------------------------------------------------------------------------------------: |
| To show analysis                                               | analyse, appraise, define, diagnose, explore, identify, investigate, observe                  |
| To summarize                                                   | assess, conclude, feature, highlight                                                          |
| To indicate control (to be stable or to maintain at a level)   | constrain, control, govern, influence, inhibit, limit, maintain, prohibit, regulate, secure   |
| To discuss findings                                            | attest, confirm, contend, demonstrate,document, indicate, reveal                              |
| To state                                                       | comment, convey, elaborate, establish,identify, propose                                       |
| To show increase                                               | advance, development, enlarge, exceed, extend, facilitate, improve,increment, maximize        |
| To show decrease                                               | alleviate, cease, decline, depress, descent, deteriorate, minimize, subside, reduce           |
| To show change                                                 | alter, accommodate, difference, evolve, fluctuate, generate, transform, transition, vary      |
| To indicate information in a figure                            | depict, display, illustrate, portray, reveal                                                  |
| To indicate information in a table                             | classify, enumerate, gives, lists, presents, summarizes                                       |
| To stress that a task has been performed in-depth              | adequately, comprehensively, exhaustively, extensively, thoroughly                            |
| To show parts                                                  | comprises, compose of, constitutes, encompasses, includes, incorporates                       |
| To indicate negative stand                                     | challenge, contradict, disagree, dispute, reject, question                                    |
| To indicate positive stand                                     | confirm, compliment, corroborate, substantiate, support, uphold, validate, verify             |
| To show approximation                                          | approximate, estimate, resemble, predict                                                      |



# Latex

## Bibliography


[How to add a page number to a bibliographic
entry.](https://tex.stackexchange.com/questions/373754/how-to-add-page-numbers-to-book-related-bibliographic-entries/373777)

> "Try using @inbook instead of @book. The .bst file of this journal has
> several definitions for citing books. When using @book in your .bib file you
> are implying that you are citing the whole book, and therefore there is no
> need for page numbergs. When using @inbook you mean to say that you are
> citing a certain part of the book. If you use @inbook the bibliography will
> show both pages and chapter of the book you are citing."

In the bst file, you can also check for chapter entries.

### Compilation errors

[Error: LaTeX Error: Something's wrong--perhaps a missing \item](https://tex.stackexchange.com/a/561933/44254)

> "In case the error keeps presenting even you already added a
> `\cite{something}` in your paper, then you have to clear the auxiliary files.
> In details, delete any files ended with .log .aux .bbl .blg."


## Diff

Install Latex diff on Debian: 

    sudo apt install latexdiff


### Latexdiff and git

Latexdiff can handle files in version control systems. I didn't know this and
checked out the old file by hand before performing the comparison. First I
describe the way I should have done it as explained in man latexdiff-vc

       latexdiff-vc -r rev1 file.tex ...
           compares file.tex with revision rev1.

       latexdiff-vc -r rev1 -r rev2 file.tex ...
           compares revisions rev1 and rev2 of file.tex.

Old way of doing things without using the latexdiff-vc helper. Generate diff
version of latex files. In the instructions below, the manuscript was made of 2
documents `template.tex ` which called `\input{content.tex}`.

Checkout contents from commit 9ce6b9 on 2020 December 1st and prepare the diff in the /tmp dir:

    # Delete and re-create a temp dir and copy everything in it
    rm -rf /tmp/article_diff/
    cp -r ~/repos/article_pub /tmp/article_diff
    # Copy the old and new versions of the manuscript to the tmp folder
    cd ~/repos/article_pub/latex_template
    git show 9ce6b9:./content.tex > /tmp/article_diff/latex_template/content_before_review.tex
    git show 9ce6b9:./template.tex > /tmp/article_diff/latex_template/template_before_review.tex
    cp content.tex /tmp/article_diff/latex_template/content_now.tex
    cp template.tex /tmp/article_diff/latex_template/template_now.tex

Generate the diff

    cd /tmp/article_diff/latex_template
    latexdiff template_before_review.tex template_now.tex > template.tex
    latexdiff content_before_review.tex content_now.tex > content.tex

Compile the diff document, enter quiet mode with “Q” if there are error messages

     latexmk -pdf -bibtex -use-make template.tex

## Makefile

Make can be use to automate the compilation of the latex file, place the
supporting figures and documents in a zip archive and subsequently remove the
intermediate files.

    # Usage:
    # make        # Generate the pdf and zip files for the submission. 
    # make render # Render the pdf, keep all automatically generated files for Latex diagnostics.
    # make clean  # Keep a copy of the pdf one level above and remove automatically generated files.
    # make zip    # Generate the zip archive of the article and figures for the submission process.
    #
    all: render clean zip

    render:
         latexmk -pdf -bibtex -use-make forests-1032372-proofreading.tex

    clean:
         cp forests-1032372-proofreading.pdf ../manuscript.pdf || echo "forests-1032372-proofreading.tex not there."
         git clean -xf

    zip: # Remove the zip archive otherwise deleted files will remain in the archive and it will be simply updated
         rm ../manuscript.zip ../figures.zip || echo "No existing zip archive to delete."
         zip ../manuscript.zip -r *
         zip ../figures.zip -r figures/*
         echo "Verify that the pdf and zip archives have been updated by checking their update time."
         ls -lh ../*.zip
	     ls -lh ../*.pdf


# Motivation

[Blog post on how to put machine learning models into
production](http://veekaybee.github.io/2020/06/09/ml-in-prod/#the-mystery-of-deploying-ml)

> "One of my favorite books ever is Bird by Bird, by Anne Lamott. It’s about
> how to write. The story she tells in the book, of how the book got its title,
> is a book report her brother had to write."

> “Thirty years ago my older brother, who was ten years old at the time, was
> trying to get a report on birds written that he’d had three months to write.
> [It] was due the next day. We were out at our family cabin in Bolinas, and he
> was at the kitchen table close to tears, surrounded by binder paper and
> pencils and unopened books on birds, immobilized by the hugeness of the task
> ahead. Then my father sat down beside him, put his arm around my brother’s
> shoulder, and said. ‘Bird by bird, buddy. Just take it bird by bird.’” 
