

# Introduction

## Folk tales

[narrative](https://en.wikipedia.org/wiki/Narrative)
> Janet Bacon: "Folk-tale, however, calls for no belief, being wholly the
> product of the imagination. In far distant ages some inventive story-teller
> was pleased to pass an idle hour with stories told of many-a-feat."

[Conte](https://fr.wikipedia.org/wiki/Conte) en français. 

[Conte merveilleux](https://fr.wikipedia.org/wiki/Conte_merveilleux)
> "Une étude récente publiée dans Royal Society Open Science en 2017 a évalué
> ces fables comme on étudie les espèces en évolution, et conclut que certains
> des contes d'occident pourraient dater d'au moins 6000 ans, à partir d'un
> corpus massif de plus de 2000 contes déposé en ligne, provenant de
> différentes cultures indo-européennes (index Aarne-Thompson-Uther, compilé en
> 2004. Toutes ces cultures indo-européennes (englobant toute l'Europe et une
> grande partie de l'Asie) descendrait des peuples Proto-Indo-européens
> néolithique établis en Europe de l'Est (10.200 BCE-2000 BCE), aussi à
> l'origine d'une grande partie des langues contemporaines" [...] des méthodes
> statistiques calquées sur celles de la phylogénétique ont été utilisées pour
> tracer les lignées d'histoires se ramifiant dans le temps, en différentes
> langues. Ainsi quand une même histoire peut être retrouvée en langues slaves
> et celtiques (ex : Jack et le Haricot magique) elle est considérée comme
> ayant un « ancêtre commun » (Proto-ouest-Indo-Européen) dont ces deux
> lignages ont divergé il y a au moins 6 800 ans. Les auteurs ont cherché à
> aussi tenir compte de la transmission horizontale d'une culture à l'autre".
The study was based on the [Aarne Thompson Uther Index](https://en.wikipedia.org/wiki/Aarne%E2%80%93Thompson%E2%80%93Uther_Index)

Several lists of folk tales available at:

* German [Märchenlexikon.de](http://www.maerchenlexikon.de/suchemotiv.htm)
* English [Folklore and mythology electronic texts](http://www.pitt.edu/~dash/folktexts.html)


[Märchen](https://de.wikipedia.org/wiki/M%C3%A4rchen)

# French 

[Portail des contes et légendes](https://fr.wikipedia.org/wiki/Portail:Contes)
Mentionne le [conte russe](https://fr.wikipedia.org/wiki/Conte_russe)

# German



# Baba Yaga

fr.wikipedia [Baba Yaga](https://fr.wikipedia.org/wiki/Baba_Yaga_(mythologie))

