---
title: "Vim Commands"
output: 
  html_document: 
    toc: yes
    toc_float: true
---


# Introduction

Vim is a modal text editor, to learn how to switch modes, start by the section
[Switch between navigation and editing mode](#navigation_edit). Large part of
this documents have been copied from the vim help accessible through:

    :help <topic>

People that I admire use vim.

# Configure vim in .vimrc

See also my vimrc file stored in [setup/.vimrc](setup/.vimrc). Many configuration options are mentioned throughout this document. 

Reload the configuration after editing it: 

    :so ~/.vimrc

Text colour. Add syntax highlight to your .vimrc

    syntax enable


## File specific .vimrc options

How to add a file extension to vim syntax highlight

    au BufNewFile,BufRead *.dump set filetype=sql

I used it to display markdown files as text files:

    au BufNewFile,BufRead *.md set filetype=txt

Make a key combination specific to latex files, to insert a citation key using
the vimtex plugin. Note: ctrl-space appears as ctrl-@ in my terminal

    au BufRead,BufNewFile *.tex inoremap <C-Space> <C-x><C-o> | inoremap <C-@> <C-x><C-o>

Prevent tab expanding to space in make files [SO answer](https://stackoverflow.com/a/158990/2641825):

    autocmd FileType make set noexpandtab


## Keyboard AZERTY, QUERTZ 

* SO [Configure vim for AZERTY keyboards](https://stackoverflow.com/questions/33245317/vim-and-azerty-keyboards)
* Reddit [AZERTY keymapping](https://www.reddit.com/r/vim/comments/2tvupe/azerty_keymapping/)
- Reddit [Vim on CZ
  QUERTZ](https://www.reddit.com/r/vim/comments/9bh6ql/vim_on_czqwertz/)

I mapped m to the end of line, maybe I should use m instead? 

    noremap m $

See also mapping below.


## Colour themes

Be sure to set terminal colour to 256 as explained in an answer
 to [a question on vi.stackexchange](https://vi.stackexchange.com/a/25310/6671)
and in the vim wiki [256 colors in vim](https://vim.fandom.com/wiki/256_colors_in_vim)

    set t_Co=256

* Slant [vim Theme gallery](https://www.slant.co/topics/480/~best-vim-color-schemes#1) 
* [Custom theme aurora](https://github.com/rafalbromirski/vim-aurora)

## Key mapping and shortcuts

See 

    :help map

Show all mappings including <leader> commands:

   :map

[How to map the ALT
key](https://vi.stackexchange.com/questions/2350/how-to-map-alt-key)
Explains who to see what key combination is actually seen by the console:

    sed -n l

I used this mapping "ALT-;" to insert the pipe "%>%" in R documents:

    " The ALT key is mapped to escape in the terminal, remap it
    " https://vi.stackexchange.com/questions/2350/how-to-map-alt-key
    execute "set <M-;>=\e;"
    autocmd FileType r inoremap <M-;> <space>%>%<CR>
    autocmd FileType rmd inoremap <M-;> <space>%>%<CR>

This didn't work because the CTRL-; is seen as ; by the terminal:

    " Try to map the CTRL+;
    autocmd FileType r inoremap <C-;> <space>%>%<CR>
    autocmd FileType rmd inoremap <C-;> <space>%>%<CR>

In the end I changed the mapping > to %>% [as explained in NVimR issue 85](https://github.com/jalvesaq/Nvim-R/issues/85):

    autocmd FileType r inoremap <buffer> > <Esc>:normal! a %>%<CR>a 
    autocmd FileType rmd inoremap <buffer> > <Esc>:normal! a %>%<CR>a 

[different mappings for CTRL+A and
CTRL+SHIFT+A](https://stackoverflow.com/questions/1506764/how-to-map-ctrla-and-ctrlshifta-differently)
It's generally not possible.

## Minimal .vimrc for bug reports

You can create a minimal .vimrc and use is by calling vim with

    vim -u /tmp/.vimrc

See for example this [bug report](https://github.com/lervag/vimtex/issues/1719)
where I used this minimal vimrc file to investigate an issue with the Vimtex
plugin. 

    set nocompatible
    let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
    let &runtimepath .= ',~/.vim/bundle/vimtex/after'
    filetype plugin indent on
    syntax enable
    " Use zathura as a PDF viewer
    let g:vimtex_view_method = 'zathura'

Or another minimal vimrc to investigate an issue with the nvim-R plugin.

    set nocompatible
    let &runtimepath  = '~/.vim/bundle/Nvim-R,' . &runtimepath
    filetype plugin indent on
    syntax enable
    let maplocalleader = ";"

    " enable vim-markdown for .Rmd files too
    " This might conflict with the Nvim-R plugin
    augroup filetypedetect_markdown
        au!
        au BufRead,BufNewFile *.Rmd set ft=markdown
    augroup END

The solution was to use 2 file types for Rmd files: `set ft=rmd.markdown`.


# Convert 

## Pandoc 

### From markdown to other formats with pandoc

Convert markdown documents to other formats such as pdf with pandoc.

Convert the current document to html

    :Pandoc 

Convert the current document to pdf

    :Pandoc pdf

Convert the current document to word

    :Pandoc docx

Other output -t options from man pandoc

• docx (Word docx)
• html or html5 (HTML, i.e.  HTML5/XHTML polyglot markup)
         • latex (LaTeX)
      • odt (OpenOffice text document)
• pptx (PowerPoint slide show)

Add a yaml front matter to specify more parameters

    ---
    title: "Songs of freedom"
    author: "Bob Marley"
    geometry: margin=0.5cm
    ---


### bibliography

To use a bibliography with the pandoc extension insert the following in the
header of the markdown file:

    bibliography: /path/to/bibliography/papers.bib

Then the bibliography file should be added to the vim variable
`b:pandoc_biblio_bibs`. You can check it was added correctly by calling: 

    :echo b:pandoc_biblio_bibs

Once the bibliography files is activated, autocomplete can be called by pressing `CTRL-X CTRL-O` (or
ctrl+space in my case) after `@`. For more see:

    :help vim-pandoc-bibliographies-module

Bibliography also works with R markdown documents, see
rmarkdown documentation [authoring bibliographies and citations](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html).

# Edit a text file

## Switch between navigation and editing mode {#navigation_edit}

Enter editing mode with i, a, o. Use escape to switch to navigation mode.
Note: I remapped the caps lock key to escape at a system level.

    i - Insert text before the cursor.
    I - Insert text before the first non-blank in the line.
    gi - Insert text in the same position as where insert mode
         was stopped last time in the current buffer.
    a - Append text after the cursor.
    A - Move to the end of the line and switch to editing mode .
    o - Begin a new line below the cursor and insert text.
    O - Begin a new line above the cursor and insert text.
    R - Enter Replace mode: Each character you type replaces an existing character.

When in editing mode you can use escape to enter the navigation mode or use:

    alt+h alt+j alt+k alt+l - Switch to navigation mode and move.
    alt+: - Switch to navigation mode and send a command.

## Edit a whole line

To edit a whole line: 

    dd to delete a whole line
    yy to copy a whole line
    p to paste the copied or deleted text after the current line or 
    P to paste the copied or deleted text before the current line 

## Edit multiple lines

You can edit multiple lines simultaneously by 
[inserting text inside a multi-line selection in Vim](https://stackoverflow.com/a/253391) :

    Use Ctrl+V to enter visual block mode
    Move down with jj to select the columns of text in the lines you want to comment.
    Then hit Shift+I and type the text you want to insert.
    Then press Escape, the inserted text will appear on all lines.
    
Similarly to enter text at the end of multiple lines ([vim.wikia](http://vim.wikia.com/wiki/Inserting_text_in_multiple_lines))

    Use Ctrl+V to enter visual block mode
    Move down with jj to select the columns of text in the lines you want to comment.
    Then hit $ to select all lines until the end of the line.
    Then press Shift+A and type the text you want to insert.
    The press Escape, the inserted text will appear at the end of all lines.

### Increment numbers in a list


Use the `range` command as explained in the [vim
wiki](https://vim.fandom.com/wiki/Making_a_list_of_numbers):

    :put =range(11,15)

Use the auto incrementation `g CTRL-A`

    :help ctrl-a

        {Visual}g CTRL-A Add [count] to the number or alphabetic character in
                the highlighted text. If several lines are
                    highlighted, each one will be incremented by an
                additional [count] (so effectively creating a
                [count] incrementing sequence).  {not in Vi}
                For Example, if you have this list of numbers:
                    1. ~
                    1. ~
                    1. ~
                    1. ~
                Move to the second "1." and Visually select three
                lines, pressing g CTRL-A results in:
                    1. ~
                    2. ~
                    3. ~
                    4. ~

Other example from the vim wiki:

    my_array[0] = 0;

Then copy it using `Y6p` (copy the line and paste it six times). The result is:

    my_array[0] = 0;
    my_array[0] = 0;
    my_array[0] = 0;
    my_array[0] = 0;
    my_array[0] = 0;
    my_array[0] = 0;
    my_array[0] = 0;

Then select the lines from the second line onwards and use `g CTRL-A` to get: 

    my_array[0] = 0;
    my_array[1] = 0;
    my_array[2] = 0;
    my_array[3] = 0;
    my_array[4] = 0;
    my_array[5] = 0;
    my_array[6] = 0;


### Sort lines alphabetically

Select a few lines in visual mode and

    :sort

Help sort

    With [!] the order is reversed.

        :'<,'>sort!

    With [i] case is ignored.

        :'<,'>sort i

    With [u] (u stands for unique) only keep the first of
    a sequence of identical lines

Sort outside a pattern

    When /{pattern}/ is specified and there is no [r] flag
    the text matched with {pattern} is skipped, so that
    you sort on what comes after the match.
    Instead of the slash any non-letter can be used.
    For example, to sort on the second comma-separated
    field: >
        :sort /[^,]*,/
    To sort on the text at virtual column 10 (thus
    ignoring the difference between tabs and spaces):
        :sort /.*\%10v/
    To sort on the first number in the line, no matter
    what is in front of it:
        :sort /.\{-}\ze\d/
    (Explanation: ".\{-}" matches any text, "\ze" sets the
    end of the match and \d matches a digit.)

Sort within a pattern

    With [r] sorting is done on the matching {pattern}
    instead of skipping past it as described above.
    For example, to sort on only the first three letters
    of each line: >
        :sort /\a\a\a/ r



## Align columns

The tabular plugin provides a Tabular command which can be abbreviated to
`:Tab`. To align a latex table with the tabular package. Select a few lines, then
press: 

    :'<,'>Tab /&

Similarly to align a markdown table, select a few lines, then call: 

    :'<,'>Tab /|

Align tab separated text in the current buffer (to view tsv files generated
from data frames by NVim-R for example): 

    :Tab /\t

Or enter CTRL + V and press the TAB key for a literal tab.

To have numbers right aligned

    :Tab /\t/r0

For more, see `help tabular`.

## Undo redo

    u: undo last change (can be repeated to undo preceding commands)
    Ctrl-R: Redo changes which were undone (undo the undos). 
    Compare to '.' to repeat a previous change, at the current cursor position.
    Ctrl-R will redo a previously undone change, wherever the change occurred. 


### Navigate the change list

Jump to previous or next editing position `:help g;`

> When making a change the cursor position is remembered.  One position is
> remembered for every change that can be undone, unless it is close to a
> previous change.  Two commands can be used to jump to positions of changes,
> also those that have been undone:
> 
>     						*g;* *E662*
> g;			Go to [count] older position in change list.
>     		If [count] is larger than the number of older change
>     		positions go to the oldest change.
>     		If there is no older change an error message is given.
>     		(not a motion command)
>     		{not available without the |+jumplist| feature}
> 
> 							*g,* *E663*
> g,			Go to [count] newer cursor position in change list.
> 			Just like |g;| but in the opposite direction.
> 			(not a motion command)
> 			{not available without the |+jumplist| feature}


## Replace characters

Vim help on search and replace `:help :s`

> `[range]s[ubstitute]/{pattern}/{string}/[flags] [count]`
> For each line in `[range]` replace a match of `{pattern}` with `{string}`.

For example find each occurrence of 'red' (in the current line only), and
replace it with 'green': 

    :s/red/green/g

The `s` command  means "substitute".
The `g` means "greedy", it will replace all occurrences of the word on a line 
(not just the first occurrence).

When [text is visually selected](http://vim.wikia.com/wiki/Search_and_replace_in_a_visual_selection),
press : to enter a command. The command line will automatically enter the range:

    :'<,'>

Then you can enter a replacement command such as `s/red/green/g` 
to replace each occurence of "red" with "green" 
in all lines of the visual selection. The command will appear as:

    :'<,'>s/red/green/g

Find each occurrence of 'red' in all lines (`%s`), and replace it with 'green'.

    :%s/red/green/g 

Find each occurence of foo but don't perform the replacement, only count the number of occurences

    :%s/foo/bar/n

To replace by a new line character, use `\r` instead of `\n`.
For example to insert a new line after each comma in a selection:

    :'<,'>s/,/,\r/g

To replace double line breaks by a single line brake

    :%s/\n\n/\r/g

You can use replacement to remove text. 
For example to [remove the last 2 characters of each line in a selection](https://stackoverflow.com/a/36264759/2641825) :

    :'<,'>s/..$//

### Character classes

See also patterns below.

See `:help character-classes` for a list of classes accepted in Vim with their
equivalent regex pattern, for example `\w` is equivalent to `[0-9A-Za-z_]`.
Replace all word characters by a dash (to create a markdown table division see
also collection below)

    :'<,'>s/\w/-/g

Note that this only works with ASCII characters and doesn't work with accentuated characters.
For example `smöl` gets replaced by `--ö-`.
To replace all identifier characters, use

    :'<,'>s/\i/-/g

And then `smöl` gets replaced by `----`.

### Collection 

See `:help collection`: "A collection is a sequence of characters enclosed in brackets."

	Example		matches ~
	[xyz]		any 'x', 'y' or 'z'
    [^xyz]"     anything but 'x', 'y' and 'z'
    [a-zA-Z]$	any alphabetic character at the end of a line

For example to replace all characters but the pipe (to create a separation in a
markdown table):

    :'<,'>s/[^\|]/-/g


### Convert to lower-case

[Switching case of characters](https://vim.fandom.com/wiki/Switching_case_of_characters):

    Toggle case "HellO" to "hELLo" with g~ then a movement.
    Uppercase "HellO" to "HELLO" with gU then a movement.
    Lowercase "HellO" to "hello" with gu then a movement.

For example to convert to lower case from the cursor to the end of the line: 

    gu$

To change the current line from upper to lower case: 

    guu

### Patterns

To place quotes around variables that contain a dollar sign (otherwise
interpreted as a formula start in markdown):

    :'<,'>s/\(\w*\$\)/`\1`/g

[add quotes at the start and end of each
line](https://stackoverflow.com/a/3218805/2641825)

    :%s/^\(.*\)$/"\1"/

>    s/regex/replace/ is vim command for search n replace.
>    % makes it apply throughout the file
>    ^ and $ denotes start and end of the line respectively.
>    `(.*)` captures everything in between. ( and ) needs to be escaped in vim regexes.
>    \1 puts the captured content between two quotes.

Remove bracketed references from text copied from Wikipedia.

    :'<,'>s/\[[0-9]\+\]//g


#### Numbers

Insert Markdown title marker `#` before a number at the beginning of a line

    %s/^\(\d.\)/# \1/g

Note `\0` matches the hole pattern. Use backslash-escaped parenthesis to match
a particular pattern. `\d` matches any digit.

Remove bracketed references from text copied from Wikipedia.

    :'<,'>s/\[[0-9]\+\]//g


### Replace spaces and new lines

Vim wiki [Remove unwanted
spaces](https://vim.fandom.com/wiki/Remove_unwanted_spaces#Automatically_removing_all_trailing_whitespace):

> In a search, \s finds white space (a space or a tab), and \+ finds one or
> more occurrences.
Command to replace repeated white spaces by a single white space in a selection:

    :'<,'>s/\s\+/ /g

SO [vim regex replace multiple consecutive spaces with only one
space](https://stackoverflow.com/questions/3860532/vim-regex-replace-multiple-consecutive-spaces-with-only-one-space)
proposes multiple other solutions, this one derived from Aristotle's answer
keeps indentation white spaces at the beginning of the line:

    :'<,'>s/[^\s]\zs\s\+/ /g

Remove all beginnings of line. :%s/\option\n/, /g replace all end of line by
comma + space. This cleans an html list of species for inclusion in a text.

     %s/option value=".*"//g 

This pattern replaces one or more white spaces with a pipe, to create markdown
tables:

    :'<,'>s/\s\+/|/g

This pattern removes spaces at the end of the line:

    :'<,'>s/\s*$//g


### Visual selection

To search and replace in a visual selection, select an area then press `:`. The
line will automatically begin with `:'<,'>`, you can then enter the patterns.

    :'<,'>s/search/replace/g

For [a vertical selection](https://stackoverflow.com/a/25276670/2641825), this
doesn't work automatically and you have to use 

    :'<,'>s/\%Vsearch/replace/g


## Copy, cut and paste

Copy 

    yy            The current line
    yiw           The current word
    ye            To the end of the current word
    yip           The current paragraph
    yG            To the end of the document

Paste with `P` (before) or `p` (after) the cursor.

Copy and paste in visual mode with the following instructions:

    Position the cursor where you want to begin cutting.
    Press v (or upper case V if you want to cut whole lines).
    Move the cursor to the end of what you want to cut.
    Press d to cut or y to yank (copy into the `"0` register).
    Move to where you would like to paste.
    Press P to paste before the cursor, or p to paste after. 

Copy to a system register (to be used by other programs)

    "+yy
    "+yip

See also the section on registers below and `:help "+` for more details on
system registers.


### Paste the current line many times

Press `Y6p` to copy the following line 6 times

    - example


### Paste from the system register

When pasting from the system register i.e. with `Ctrl+Shift+V` you need to prevent auto indent
otherwise vim will mess with the indentation. This can be solved with bracketed
paste, see further down below.

As explained in [Paste without autoindent](https://stackoverflow.com/a/2545242/2641825)
You can either read from the shell with:

    :r! cat 

And then paste `CTRL + SHIFT + V` the content, and `CTRL+D`.
Also works over SSH.

Or use

    :set paste
    :set nopaste

Set up a shortcut to toggle paste mode on and off with:

    set pastetoggle=<F3>

Note: I don't use paste toggle any more, bracketed paste works well.

#### Bracketed paste

[Enable bracketed paste in a session](https://stackoverflow.com/a/44507798/2641825)

    bind 'set enable-bracketed-paste on'    


### Registers

To display the content of all registers:

    :registers

For example yank the word "yank", delete the word "delete" and copy the word
"system" outside of vim in any program will give you the following registers: 

    :registers
    --- Registers ---
    ""   delete
    "0   yank
    "-   delete
    "*   system
    "+   system
    ".   ^@yank^@delete^@


### Replace a word

[How can I do a change word in vim using the current paste
buffer](https://unix.stackexchange.com/questions/88714/how-can-i-do-a-change-word-in-vim-using-the-current-paste-buffer)


Select the current word, then select the word to replace and paste

    ye
    vep

Or select the current word, then paste and delete the word to replace

    ye
    Plde

Note this works only for one replacement because the yank register is then
replaced with the deleted word.

## Indentation

Indentation replaced by spaces, add this to the ~/.vimrc file

    set tabstop=4
    set expandtab
    set softtabstop=4
    set shiftwidth=4
    filetype indent on 

More details on vim indentation in the [python
wiki](https://wiki.python.org/moin/Vim). In particular the page [How to stop
auto indentation](https://vim.fandom.com/wiki/How_to_stop_auto_indenting)
explains how to display indentation setting for the current file type: 

    :verbose set ai? cin? cink? cino? si? inde? indk?


## Repeat Commands

[Repeating commands, Vim scripts and debugging](http://vimhelp.appspot.com/repeat.txt.html)

## Save and rename a file

Save the current file

    :w

Save under a new name (save as) and edit that file

    :sav

SO [save as a new file and continue editing the original one](https://stackoverflow.com/questions/4980168/how-to-save-as-a-new-file-and-keep-working-on-the-original-one-in-vim)

To move or rename a file within the vim file explorer:

    R

## Wrap lines

Thoughtbot.com [Wrap existing block of text to 80 characters](https://thoughtbot.com/blog/wrap-existing-text-at-80-characters-in-vim):

    :set textwidth=80

Apply automatically to markdown files, by adding this to .vimrc 

    au BufRead,BufNewFile *.md setlocal textwidth=80

To format the text, select it with v and up or down movements, and press 

    gq

To disable auto wrapping, call

    :set formatoptions=cq


# Select and visual mode

Vim documentation

    :help visual-use

[Difference between visual and select
mode](https://vi.stackexchange.com/questions/4891/what-is-the-select-mode-and-when-is-it-relevant-to-use-it) 

Various ways to select text in visual mode

    vt<char> - till before a given character
    vf<char> - till a given character

Select the current paragraph:

    vip

Select the current word:

    viw

Select what is in the current parenthesis block

    vi(

Select what is inside the current quote block

    vi"

These selection methods can also be used to delete `diw` and yank `yiw`.

# Enter commands, save and quit

To enter edit mode:

    i

To enter command mode:

    escape

To exit vim, go in command mode and enter the following command:

    :q

To exit without saving the content of the file:

    :q!

To save the content of the file:

    :w

If you accidentally press CTRL+S the [terminal will hang](https://askubuntu.com/a/264253/315347)
Press `CTRL+Q` to regain control.
See also [Ctrl-s hang terminal emulator?](https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator)
which provides a workaround: entering `stty -ixon` in .bashrc. 

To save content and exit:

    :wq

# Email with Mutt

See also the [debian.html] page. The Arch Linux [wiki page on
Mutt](https://wiki.archlinux.org/index.php/Mutt#Installation) has a section
explaining how to set it up with vim.

# Help

    :help - vim help
    :help commandname - help on a particular command
    :h commandname - help on a particular command
    CTRL+] - jump to a highlighted topic
    CTRL+T - jump backwards

[HTML version of the Vim help pages](http://vimhelp.appspot.com/)
kept up-to-date automatically from the 
[Vim source repository](https://github.com/vim/vim).

## Messages

Did you see warning messages but they disappeared before you have had time to
read them? Type the command |:messages| in Normal mode to see them again.
(copied from nvim-r help)

# Insert 

## Current file name

[Insert the current file name in VIM](https://unix.stackexchange.com/questions/57555/how-do-i-insert-the-current-filename-into-the-contents-in-vim)
In insert mode press: 

    <c-r>%

In normal mode: 

    :r! echo %

## Content of another file

In normal mode, insert the content of another file:

    :read /tmp/newdir/file1.txt

Insert the content of a file from the network:

    :Nread https://www.wikipedia.org/

For more, see `:help Nread`.

## Date or time

Vim wiki [insert date or
time](https://vim.fandom.com/wiki/Insert_current_date_or_time)

I added the following command to my .vimrc:

    command! Date put =strftime('%Y-%m-%d')

# Multiple files, buffers and windows

## Buffers

    :e filename - edit another file 
    :ls         - show current buffers
    :b 2        - open buffer #2 in this window
    :b filename - open buffer #filename in this window
    :bd         - close the current buffer (! to forget changes)
    :bd filename -close a buffer by name 

Reload the file in the current buffer: 

    :e


## Quickfix window

Open the quickfix window with:

    :copen

The result of some search operation seach as grep can be displayed in the quick
fix window.

## Tabs should be called workspaces

[Why do vim experts prefer buffers over tabs?](https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs/26710166#26710166)
> ""Vim experts" don't prefer buffers over tabs: they use buffers as the file
> proxies they are and tab pages as the workspaces they are. Buffers and tab
> pages have different purposes"

Open a file in a new tab

    :tabnew {file}

Move to the next tab

    gt

Move to the previous tab

    gT

Open the file under the cursor in a new tab


    CTRL-W gf	Open a new tab page and edit the file name under the cursor.
            See |CTRL-W_gf|.

    CTRL-W gF	Open a new tab page and edit the file name under the cursor
            and jump to the line number following the file name.
            See |CTRL-W_gF|.

See `:help tabpage` for more instructions.


## Window split

    :sp[lit] filename  - split window and load another file
    :10sp - specify the split height with a number
    :vs[plit] - same but split vertically  
    ctrl-w up arrow - move cursor up a window
    ctrl-w ctrl-w   - move cursor to another window (cycle)
    ctrl-w_         - maximize current window
    ctrl-w=         - make all equal size
    CTRL+z - suspend the process and get back to the shell
    fg - get back to vim

[Easier split navigations](https://robots.thoughtbot.com/vim-splits-move-faster-and-more-naturally#easier-split-navigations)

    nnoremap <C-J> <C-W><C-J>
    nnoremap <C-K> <C-W><C-K>
    nnoremap <C-L> <C-W><C-L>
    nnoremap <C-H> <C-W><C-H> 

Natural split opening

    set splitbelow
    set splitright

Open an existing buffer (from the buffer list) in a new split

    :sb buffername

For a vertical split

    :vert sb buffername


### Open vim with two files in two splits or more

[ViM Stack
exchange](https://vi.stackexchange.com/questions/732/how-to-open-multiple-files-in-split-mode)
Open 2 files in 2 horizontal splits

    vim -o file1.md file2.md

Limit the number of splits

    vim -o2 *.md

Open files in vertical splits

    vim -O file1.md file2.md


### Split resize

Set current window height to 10 lines

    res 10

Set current window width to 100 characters

    vertical res 100

See `:help resize` for more commands. There are many possible key combinations
to resize the window. 

    :res[ize] [N]
    CTRL-W CTRL-_					*CTRL-W_CTRL-_* *CTRL-W__*
    CTRL-W _	Set current window height to N (default: highest possible).
    z{nr}<CR>	Set current window height to {nr}.

Change the height of the current window by increments of 10:

    :res +10

Change the with of the current window by increments of 10:

    :vert res +10

Set the height of the terminal buffer to 10 lines

    :set termwinsize=10x0


### Split zoom in and out

[zoom windows in vim](https://stackoverflow.com/a/30362564/2641825)

    c-w-| to have window take over (if using vsplits). 
    c-w-_ for horizontal splits
    c-w-= to restore. 

### Split and buffers

[Delete buffer without losing the split
window](https://stackoverflow.com/questions/4465095/vim-delete-buffer-without-losing-the-split-window)

    bp|bd #

## Vim and Tmux

See the [bash](bash.html) page for the tmux side of the configuration.

I use the [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator)

It doesn't work in a terminal buffer because of conflicts with fuzzy file search. 
[issue 172](https://github.com/christoomey/vim-tmux-navigator/pull/172)

[vim-tmux-navigator to use tmux prefix instead of C-[hjkl]](https://superuser.com/questions/1467829/vim-tmux-navigator-to-use-tmux-prefix-instead-of-c-hjkl)

busnag.com [tmux and vim](https://www.bugsnag.com/blog/tmux-and-vim)
> " like many vim users, I edited my .vimrc to simplify split navigation, so
> that I can jump between vim splits using ctrl-j, ctrl-k, etc. 

reddit [python workflow with terminal using tmux](https://www.reddit.com/r/vim/comments/chdl60/python_workflow_with_terminal_using_tmux/)
> "Finally, I have Ctrl+[hjkl] setup such that I can navigate seamlessly between vim and tmux panes."


# Navigate

## Display line numbers

 Display line numbers

    :set nu

Disable line numbers

    :set nonu

Enter `:line number` to jump to a particular line number.

## Explore files

Vim comes with a file explorer:

    :Explore
    :E

The file explorer can also be opened in tabs or splits:

    :Se
    :Le
    :Ve
    :Te

To open a file in vim press enter. To open a file better suited for other
applications, such as a pdf, an html file or an image, press 

    x

To [return to file editing without opening any
file](https://stackoverflow.com/questions/27691792/vim-quit-close-netrw-without-selecting-any-file)
(and to switch back and forth between editing and explorer):

    :Rexplore
    :Re

In the file explorer, also called "netrw", pressing `s` changes the way files
are sorted by name, time, size. Pressing `x` on a file name opens that file
with the relevant system program associated with it. For example pressing `x`
on a pdf file opens that file in the evince reader on my system. Pressing `x`
on a folder name opens the files explorer. The `i` key switches between
different view types, tree view, detailed view, summarised view. To rename a
file press `R` and to delete a file press `D`.

To create a new file in the current directory visible in the explorer, press:

    %

This is also works to create a new directory and file.

To move or rename a file within the explorer:

    R

A blog post on 
[netrw](https://shapeshed.com/vim-netrw/), vim's file browser.
Explains how to turn the banner off: 

    let g:netrw_banner = 0

You can put the banner back on by pressing `I`.


## Go to file

Open the file under the cursor, in the current window:

    gF

Open the file under the cursor, in a new window:

    gf

If the file is a pdf, an image or a web link, use: 

    gx

See :help gx for more information on how vim handles the file opening in
various operating systems.


## Jump back and forth

Vim wiki [jumping to previously visited
locations](https://vim.fandom.com/wiki/Jumping_to_previously_visited_locations)
> "Like a web browser, you can go back, then forward:"

    Press Ctrl-O to jump back to the previous (older) location.
    Press Ctrl-I (same as Tab) to jump forward to the next (newer) location. 


## Markdown Table of Content

Display a list of first level header in a markdown document (found in quick markdown navigation/TOC)

    :g/^# /#

See also :

* The markdown TOC extension for vim.
* [Vim markdown composer](https://github.com/euclio/vim-markdown-composer/blob/master/README.md)
    a plugin that adds asynchronous Markdown preview to Neovim and Vim.


###  Vim-markdown TOC (not used)

In [this
question](https://vi.stackexchange.com/questions/24848/how-to-use-vim-markdown-toc-for-documents-with-extension-other-than-md),
I managed to create an auto command to activate vim-markdown for Rmd files. But
now that I start using Nvim-R more intensively, I hit [vim-markdown issue
263](https://github.com/plasticboy/vim-markdown/issues/263): activating
vim-markdown removes syntax highlighting and auto completion of the R code
chunks. I first extracted the Toc function into a small plugin. Then started
using the Voom plugin.


### Vim-pandoc TOC (not used)

The vim-pandoc plugin also provides a table of content for markdown files,
accessible through the `:TOC` command.


### Voom TOC (used)

I chose to create the table of content with the [Voom
plugin](https://github.com/vim-voom/VOoM) based on a suggestion on [Nvim-R
issue 505](https://github.com/jalvesaq/Nvim-R/issues/505). I have this in my
`.vimrc`: 

    let voom_ft_modes = {'markdown': 'pandoc', 'rmd': 'pandoc', 'tex': 'latex'}
    au BufRead,BufNewFile *.Rmd command! Toc Voom 

In the outline pane, press enter once to display the corresponding header in
the body pane. Press enter a second time to move the cursor to the body pane.
In the body pane, press enter once to display the position of the cursor in the
outline pane. Press enter a second time to move to the corresponding place in
the outline pane. 

Key mappings in the outline pane:

    jk  move up and down in the outline pane. The view pane doesn't move.
    up/down arrow move and display the corresponding sections in the view pane.
    <space> fold/unfold the current node.
    left/right arrow fold/unfold the current node.
    O Recursively expand the current node and its siblings.
    C Recursively contract the current node and its siblings.

It's also possible to move nodes with cut `dd` and paste behaviour `pp` and to
promote/demote them as such:

    <LocalLeader>l Move node(s) left, that is promote.
    <LocalLeader>r Move node(s) right, that is demote.

> By default, commands Cut, Copy, Paste use the "+ register, that is the system
> clipboard (|registers|, |quote+|). This means you can move nodes between
> outlines in different instances of Vim, or copy/paste in other applications.

## Move up, down, left, right

In command mode, the following motions are activated:

    :help left-right-motion
    j,k move up down
    h,l move left right
    b,w move previous or next word
    ctrl+b, ctrl+d move page up or page down
    {number} G go to line number 
    H,L,M move to top, bottom and middle of visible window
    ^, $ move to the begining or end of a line
    in addition, I mapped m to $

Note on motion with wrapped lines:
[Move cursor by display lines when wrapping](https://vim.fandom.com/wiki/Move_cursor_by_display_lines_when_wrapping)

## Quick fix window

Help 

    :help quickfix


## Search in the current file 

Use `"/"` to search, then n forward and N backwards `"*"` to search for the word
under the cursor (you can also create a mapping to search for a selected text)

Use `:g/pattern` to display a list of all search result in the document. 

Search all occurrences of a pattern and populate the quick fix window:

    :vim /pattern/ % | cw


### Highlight search matches

Define a new highlight group and use it to highlight matches

    :highlight newgroup ctermbg=green guibg=green
    :match newgroup /TODO/

Clear the match pattern

    :match

Display the list of all highlight groups

    :highlight

Use existing highlight groups

    :match String /i/
    :2match Character /o/
    :3match Label /a/


## Search in multiple files

Define the `F3` shortcut in `.vimrc` to recursively search all
files in the present working directory for the word under the cursor:

    nmap <F3> :vimgrep /<C-R><C-W>/ **<CR>

Alternatively, use git grep from the fugitive plugin:

    :Ggrep pattern

Both `vimgrep` and `Ggrep` will open a quick fix window displaying file names
and line numbers for each matching character string.

[open files on the match lines given by grep](https://stackoverflow.com/questions/2653419/vim-open-files-of-the-matches-on-the-lines-given-by-grep)

    :copen
    :grep -r pattern .

or specify specific files extensions

    :grep -r pattern *.py


## Working directory

Display the present working directory

    :pwd

[Set working directory to the current file](http://vim.wikia.com/wiki/Set_working_directory_to_the_current_file) (for all windows):

    :cd %:p:h

Set working directory to the current file, for the current window only

    :lcd %:p:h

In these commands, % gives the name of the current file, %:p gives its full path, and %:p:h gives its directory (the "head" of the full path). 

Automatically change the working directory to the file currently edited

    set autochdir

autochdir conflicts with the ctags plugin taglist [as explained
here](https://vi.stackexchange.com/questions/13960/how-to-browse-tags-when-autochdir-is-set)
so I deactivated it. 

# Plugins

Plugins are mentioned in diverse section of this document. 
This section is mostly to list plugins I used and potentially interesting plugins. 

Display plugins I currently use with vundle: 

    :PluginList

Copy of the list from my `.vimrc`:

    " Colour themes for Vim
    Plugin 'morhetz/gruvbox'
    Plugin 'nanotech/jellybeans.vim'
    " Code structure i.e. table of content of classes, methods and functions
    Plugin 'yegappan/taglist'
    " Git interface 
    Plugin 'tpope/vim-fugitive'
    " Latex editing
    Plugin 'vim-latex/vim-latex'
    " Markdown toc navigation
    Plugin 'godlygeek/tabular'
    Plugin 'plasticboy/vim-markdown'
    " Python autocompletion 
    Plugin 'davidhalter/jedi-vim'
    " Python linter
    Plugin 'dense-analysis/ale' 
    " R programming
    Plugin 'jalvesaq/Nvim-R'

I also use a spell checker. 

Other plugins installed in the default vim repo:

    :r ! ls ~/.vim/pack/plugins/start/
    indentpython.vim
    pytest.vim
    vim-slime
    vim-tmux-navigator

Potentially useful plugins

* [fugitive](https://github.com/tpope/vim-fugitive) git integration
* [Quick fix preview](https://github.com/bfrg/vim-qf-preview)
* Fuzzy search 
* fzf command line fuzzy finder [fzf](https://github.com/junegunn/fzf)
* File explorer 
    * or simply use the native vim explorer `:Explore`
* Minibufexplorer and SO post on [alternatives to minibufexplorer](https://stackoverflow.com/questions/4865132/an-alternative-to-minibufexplorer-vim)
* [Vimtex](https://github.com/lervag/vimtex#alternatives) 
  vim plugin for editing LaTeX files. 
* [distribution spf13](https://vim.spf13.com/) probably not recommended but the home page contains a list of interesting plugins. 
*
See also the section programming with vim below for language specific plugins. 

## Create a plugin

* [plugin layout in the dark ages](https://learnvimscriptthehardway.stevelosh.com/chapters/42.html)
  explains how to create file type plugins.

I'm trying to extract a table of content functionality from a plugin that does
many other things I don't need. 

* https://vi.stackexchange.com/questions/16470/setting-syntax-in-ftplugin

I extracted the function into a plugin called
[markdown-toc-toc](https://github.com/paulrougieux/markdown-toc-toc) I placed
the plugin in ~/.vim/pack/plugins/start/markdown-toc-toc and this fixes my
issue. I now have both Nvim-R autocompletion and syntax highlight working
correctly in R markdown chunks as well as a table of content for the markdown
titles. Later on, I moved to the Voom plugin for the table of content.


## Deactivate a plugin

To temporarily deactivate a plugin in a session. 


## Detect slow plugins

[How to see which plugins are making Vim
slow?](https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow)

> "You can use built-in profiling support: after launching vim do"

    :profile start profile.log
    :profile func *
    :profile file *
    " At this point do slow actions
    :profile pause
    :noautocmd qall!

> "If you're having problems with screen update operations (^L, scrolling, etc)
> being slow, your problem may be an inefficient syntax highlighting file. You
> can test this by temporarily disabling syntax highlighting"

    :syn off

To profile the syntax file 

    Open a file that causes syntax highlighting performance issues.
    Run :syntime on to start profiling.
    Scroll through the file a bit.
    Run :syntime report to generate a report. The patterns listed first in the report are the ones which took the most time to process.



The matchparen plugin seemed to be slow on large markdown documents. It's part
of the vim distribution and loaded by default. vi.stackexchange [matchpairs
makes vim
slow](https://vi.stackexchange.com/questions/5128/matchpairs-makes-vim-slow).
But it was called by the Pandoc syntax highlight file.


## Install plugins with vim's built-in plugin support

Install slime with Vim's built-in package support (since Vim 7.4.1528):

     mkdir -p ~/.vim/pack/plugins/start
     cd ~/.vim/pack/plugins/start
     git clone https://github.com/jpalardy/vim-slime.git

## Install plugins with Vundle

Since there is a built-in plugin support, maybe I don't need Vundle after all? 

Edit your .vimrc and add the following at the beginning

    set nocompatible              " be iMproved, required
    filetype off                  " required

    " set the runtime path to include Vundle and initialize
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    " alternatively, pass a path where Vundle should install plugins
    "call vundle#begin('~/some/path/here')

    " let Vundle manage Vundle, required
    Plugin 'VundleVim/Vundle.vim'
    " Navigate markdown toc
    Plugin 'godlygeek/tabular'
    Plugin 'plasticboy/vim-markdown'
    Plugin 'tpope/vim-fugitive'
    Plugin 'jpalardy/vim-slime'

    " All of your Plugins must be added before the following line
    call vundle#end()            " required
    filetype plugin indent on    " required
    " To ignore plugin indent changes, instead use:
    "filetype plugin on
    "
    " Brief help
    " :PluginList       - lists configured plugins
    " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
    " :PluginSearch foo - searches for foo; append `!` to refresh local cache
    " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
    "
    " see :h vundle for more details or wiki for FAQ
    " Put your non-Plugin stuff after this line


Install all plugins configured in your `.vimrc`.

    :PluginInstall


# Programming languages 

## Latex editing


### vim Latex

[vim-latex](https://github.com/vim-latex/vim-latex) the one I used first.

* Was complaining about my makefile, that it didn't include a dvi section
* Was creating nice taglist but with duplicated tags.

### Vimtex

[vimtex](https://github.com/lervag/vimtex#alternatives) is more recent compared to vim-latex 

* Completion uses omni completion, see `:help compl-omni` with 
    CTRL-X CTRL-O
* doesn't complain about my minimalistic makefile
* doesn't add anything to the taglist (maybe I should use gutentag?) but there is a table of content buffer.

Usage as explained in ̀`:help vimtex-default-mappings`: 

  ---------------------------------------------------------------------~
   LHS              RHS                                          MODE~
  ---------------------------------------------------------------------~
   <localleader>lv  |<plug>(vimtex-view)|                           `n`
   <localleader>lr  |<plug>(vimtex-reverse-search)|                 `n`
   <localleader>ll  |<plug>(vimtex-compile)|                        `n`
  ---------------------------------------------------------------------~

I mapped `<localleader>` to `;`.

Display a table of content:

    :VimtexTocOpen
    :VimtexTocToggle

Define a shorter command name `Toc`, by placing this in the .vimrc

    au BufRead,BufNewFile *.tex command! Toc VimtexTocOpen

I first ran into this error when viewing git diffs or when jumping back to the tex file with 
Ctrl-O

    Error detected while processing BufRead Autocommands for "*.tex":
    E174: Command already exists: add ! to replace it: Toc VimtexTocOpen

Because I had the autocommand defined this way:

    au BufRead,BufNewFile *.tex command Toc VimtexTocOpen

Compile 

    :VimtexCompile

Install prerequisite to view pdf files with forward (from vim to the pdf
viewer) and backward (from the pdf viewer to vim) search. Note: Forward and
backward search are not available for evince [issue
179](https://github.com/lervag/vimtex/issues/179).

    sudo apt install zathura
    sudo apt install xdotool

This bug report pushed me to learn about xdotool and xprop. 

There was a issue with the focus not moving to the zathura viewer.
I reported it as [issue #1719](https://github.com/lervag/vimtex/issues/1719).
The first step was to add client server support to vim. 
I asked a question on [how to install vim with clientserver
support](https://vi.stackexchange.com/questions/26025/how-to-install-vim-with-clientserver-on-debian).
But the issue remained even with client server enabled in vim. 

The second step was related to the fact that Debian 10 Buster uses wayland as a
window manager. To force the use of x11 for zathura, in debian a zathura
wrapper script containing:

    #!/usr/bin/bash
    GDK_BACKEND=x11 /usr/bin/zathura "$@"

Can be placed under the default user bin located at ~/.local/bin.
This is one of the first element of the `$PATH` environment variable. 

## Python programming

Plugins
* [Python mode](https://github.com/python-mode/python-mode)
* [Jedi](https://github.com/python-mode/python-mode) it's incompatible with python mode (according to the readme)
    * more explanations in the Jedi section below
* [vim ipython](https://github.com/ivanov/vim-ipython)
* [vim-test] see also the tests section below.

Blog posts

* wiki.python.org [vim](https://wiki.python.org/moin/Vim) mentions:
    * [vim as a python IDE](https://200ok.ch/posts/vim-as-python-ide.html)
* realpython.com [Vim and python a match made in heaven](https://realpython.com/vim-and-python-a-match-made-in-heaven/)
* reddit [python-mode or Jedi?](https://www.reddit.com/r/Python/comments/5f2fri/developing_python_with_vim_what_plugin_to_choose/)
     python mode seems to be for starting, most people turn the features off.
* SO [Running python code in VIM](https://stackoverflow.com/questions/18948491/running-python-code-in-vim)
Make sure your files start with a shebang.
* Plug-in [Jupyter vim](https://github.com/jupyter-vim/jupyter-vim)
* Vim on Python wiki (set softtabstop=4) or your  python development environment (set tabstop=4 and set softtabstop=4)
* full stack python [vim](https://www.fullstackpython.com/vim.html)
* [vim and python script debugging](https://stackoverflow.com/questions/1901528/vim-and-python-scripts-debugging)

Reddit [python workflow with terminal using tmux](https://www.reddit.com/r/vim/comments/chdl60/python_workflow_with_terminal_using_tmux/)

> "I run my scripts using
> 
> ipython -i script.py
> 
> That way I drop to an ipython shell whenever it breaks or finishes running. I also insert
> 
> from ipython import embed; embed();
> 
> Instead of using pdb. Its really neat."


### Ale Linter

I use the Ale linter to check the code quality. 

To copy code it's preferable to deactivate the 2 characters columns used by ale
as explained in [Is it possible to disable the column on the left that is
created by
ALE?](https://vi.stackexchange.com/questions/21563/is-it-possible-to-disable-the-column-on-the-left-that-is-created-by-ale)

    :set signcolumn=no

The 2 characters column can later be shown again with 

    :set signcolumn=yes


### Jedi vim

* [Jedi](https://github.com/davidhalter/jedi) autocompletion, also used by
    ipython.
* [Jedi vim
    documentation](https://github.com/davidhalter/jedi-vim/blob/master/doc/jedi-vim.txt)

Jedi Installation required enabling python mode in vim, available inside this
Debian package:

    sudo apt install vim-nox

Autocomplete is turned on to complete a word, press:

    Ctrl+Space

To cycle through proposition you can use `Ctrl+space` again or:

    Ctrl+P
    Ctrl+N

Enter for example a module name, then use Ctrl+N and
Ctrl+P to choose among the objects and functions in that module. 

Jump to definition:

    <leader>d

I remapped the `<leader>` key to `,` in my .vimrc

    :let mapleader = ","

See above section on navigation, you can use `Ctrl-O` to jump back and
`Ctrl-I`to jump forward.


## R programming

* Medium Xiaoou WANG [How to turn vim into a perfect, better R IDE and
    Rmarkdown writer than Rstudio (part
    I)](https://medium.com/@xiaoouwang/how-to-turn-vim-into-a-perfect-better-r-ide-and-rmarkdown-writer-than-rstudio-part-i-48e1293c9c05)
* reddit [R programmers, do you prefer vim or Rstudio?](https://www.reddit.com/r/vim/comments/92x9u8/r_programmers_do_you_prefer_vim_to_rstudio/)
    > "Vim with fzf helps open these subsection code files super easily, ag helps
    > me find keywords across all the files in my code folder, ctags helps me find
    > functions I've defined, ale tells where I've made some trivial mistake,
    > gitgutter tells me where I've made changes I'd maybe like to revisit later. I
    > find these plugins alone make coding in vim much easier than R studio and
    > they aren't even R specific."
* free code camp [Turning vim into an
IDE](https://www.freecodecamp.org/news/turning-vim-into-an-r-ide-cd9602e8c217/)
    Uses [Nvim-R](https://github.com/jalvesaq/Nvim-R)
    which works with both vim and neo vim

### Nvim-R

[Nvim-R](https://github.com/jalvesaq/Nvim-R) supports knitr and mappings can be
defined for example: 

   RSendChunk
   RDSendChunk

I mapped the local leader key to ";" by adding the following to my .vimrc:

    let maplocalleader = ";"

Start R

* Start R (default)                                  ;rf

Sending code to R:

* Line                                               ;l
* Line (and down)                                    ;d
* Line (and write output as a comment)               ;o
* Chunk (cur, echo and down)                         ;ca
* Chunk (cur)                                        ;cc
* Chunk (cur, echo)                                  ;ce
* Chunk (cur, down)                                  ;cd
* Chunk (from first to here)                         ;ch
* Selection                                          ;ss
* Selection (echo)                                   ;se
* Selection (evaluate and insert output in new tab)  ;so
* File                                               ;aa
* File (echo)                                        ;ae
* File (open .Rout)                                  ;ao
  
Object browser
    
* Open/Close the object browser                      ;ro
* Expand (all lists)                                 ;r=
* Collapse (all lists)                               ;r-
* Toggle (cur)                                     Enter

On the code, when the cursor is on a data frame:

* Names (cur)                                        ;rn
* Structure (cur)                                    ;rt
* View data.frame (cur) in new tab                   ;rv
* View data.frame (cur) in horizontal split          ;vs
* View data.frame (cur) in vertical split            ;vv
* Selection (evaluate and insert output in new tab)  ;so

Edit code

* Toggle comment (line, sel)                         ;xx

Help on a function ;rh

### Tags

To generate tags for R files contained in a project's `R/` subfolder, define the
following bash function: 

```{bash eval=FALSE}
rtags() {
    Rscript -e "rtags(ofile = 'et'); nvimcom::etags2ctags('et', 'tags'); unlink('et')"  && cat tags
}
```
Usage:

    cd ~/rp/eutradeflows/R  && rtags

The bash function above was inspired by NVimR's `:RBuildTags` command. 
Alternatively, you can call the line starting with `rtags` above from within
Vim with `:RBuildTags`. But this requires moving to the `/R` subfolder
first and moving back to the project root after having created the tags:

    R > setwd("R") # R command

    :RBuildTags # VIM command

    R > setwd("..") # R command

Display tag files currently seen by vim: 

    :set tags

Navigate tag files with `CTRL+]` (`CTRL+ù` on my setup).

https://stackoverflow.com/a/14465438/2641825

An NVim-R issue about displaying a nice [list of tags for R
functions](https://github.com/jalvesaq/Nvim-R/issues/517).

I have added some of my packages to the tag files always seen by vim:

    autocmd FileType r set tags+=~/rp/tradeharvester/R/tags,~/rp/eutradeflows/R/tags
    autocmd FileType rmd set tags+=~/rp/tradeharvester/R/tags,~/rp/eutradeflows/R/tags

Setting up tags as explained in :help Nvim-R

> You could, for example, download and unpack R's source code, start R inside
> the ~/.cache/Nvim-R directory and do the following commands:

     rtags(path = "/path/to/R/source/code", recursive = TRUE, ofile = "RTAGS")
     etags2ctags("RTAGS", "Rtags")

> Then, you would quit R and do the following command in the terminal emulator:

     ctags --languages=C,Fortran,Java,Tcl -R -f RsrcTags /path/to/R/source/code

> Finally, you would put the following in your |vimrc|, optionally inside an
> |autocmd-group|:

     autocmd FileType r set tags+=~/.cache/Nvim-R/Rtags,~/.cache/Nvim-R/RsrcTags
     autocmd FileType rnoweb set tags+=~/.cache/Nvim-R/Rtags,~/.cache/Nvim-R/RsrcTags

Config example 
https://gist.github.com/tgirke/7a7c197b443243937f68c422e5471899


### Knitr issue

Posted this to https://github.com/jalvesaq/Nvim-R/issues/509

One solution based on `:help Nvim-R-key-bindings`, is to use `SendCmdToR` as such:

    :call g:SendCmdToR("setwd(opts_knit$get()$root.dir)")

I mapped this to `<localleader>wd` by editing my `.vimrc` as follows:

    map <silent> <LocalLeader>wd  :call g:SendCmdToR("setwd(opts_knit$get()$root.dir)")<CR>

To use it, I run the setup chunk with `<localleader>ca`, then I call `<localleader>wd`.


# Programming tools

## Debugger

vi.stackexchange [Python debugging](https://vi.stackexchange.com/questions/17962/python-debugging)
[vimpdb](https://github.com/gotcha/vimpdb)

## Git fugitive

Once the fugitive plugin is installed the `:G` command can be used run any git
command, such as:

    :G status
    :G pull 
    :G log

The output of these command may appear in a vim buffer, or it may appear in a
terminal, depending on whether or not fugitive has a special way to handle the
output of git.

### Summary buffer

You can also call the command alone to open a fugitive summary
buffer:

    :G

Within this summary buffer many things can be done with mappings. 
Move to the next file and expand inline diffs:
    
    i

Expand inline diffs of the file under the cursor :

    >

Remove the inline diff of the file under the cursor.

    <

Perform a horizontal diff on the file under the cursor.

    dd

Perform a vertical diff on the file under the cursor.

    dv

Stage (add) or unstage (reset) the file under the cursor:

    a
    -

Create a commit

    cc

Discard the change under the cursor.  This uses `checkout` or `clean` under the
hood.  A command is echoed that shows how to undo the change.  Consult
`:messages` to see it again.  You can use this during a merge conflict do
discard "our" changes (--theirs) in the "Unstaged" section or discard "their"
changes (--ours) in the "Staged" section.

    X


### Git commands within vim

Blame the current file

    :G blame

Git log of the current file only

    :G log %

Since the word diff provided by fugitive is not colourized, I created an alias to display a word diff

    :Gwdiff

It's defined in .vimrc as:

    command! Gwdiff vert term git diff --word-diff

## Linter

I have installed the [ALE linter](https://github.com/dense-analysis/ale) and use it for python code.
To temporarily disable ALE in a buffer:

    :let b:ale_enabled = 0

To enable it:

    :let b:ale_enabled = 1

For the python options, see:

    :h ale-python-options

I've added this option to my .vimrc to show which linter is complaining

    let g:ale_echo_msg_format = '[%linter%] %s'

The linters I see most in python code are pylint and flake8.

Pylint complains about [variable names that are too short](https://github.com/PyCQA/pylint/issues/2018)

See the [python page](python.html) for the configuration details of the
linters.


## Navigate code with tags 

Install [universal ctags](https://github.com/universal-ctags/ctags), the updated version

    sudo apt install universal-ctags

This is an updated version exuberant ctags (not updated since 2009).

I have defined shortcuts for the French AZERTY keyboard. I use `ctrl %` to jump to a
tag, because it's besides the letter M, accessible with the little finger.

- Reddit [comparison of taglist and
  tagbar](https://www.reddit.com/r/vim/comments/s0j8v/what_plugin_is_used_on_the_topright_of_this/)

Help page for NvimR
```
:help RBuildTags
```


### Taglist 

Install the taglist plugin with vundle

    Plugin 'yegappan/taglist'

[taglist manual](http://vim-taglist.sourceforge.net/manual.html#taglist-internet)

> "You can open the taglist window using the ":TlistOpen" or the ":TlistToggle"
> commands. The ":TlistOpen" command opens the taglist window and jumps to it.
> The ":TlistToggle" command opens or closes (toggle) the taglist window and the
> cursor remains in the current window."

Help:

    :help taglist-intro

### Tagbar 

I don't use it because it opens only one file in the list, see feature request
[open multiple files like taglist 31](https://github.com/majutsushi/tagbar/issues/31)

An alternative plugin called [tagbar](https://github.com/majutsushi/tagbar) enables 

    https://github.com/majutsushi/tagbar

[latex related issues]()
[Issue 336 too much space](https://github.com/majutsushi/tagbar/issues/336)
Recommends: 

    let g:tagbar_compact = 1

Here are the settings I used when I tried tagbar:

    " Settings for plugin 'majutsushi/tagbar'
    " Toggle tagbar
    nmap <F8> :TagbarToggle<CR>
    " Place tagbar to the left
    let g:tagbar_left = 1
    " Place lines closer together
    let g:tagbar_compact = 1

## Slime to send code to target terminal

[vim slime](https://github.com/jpalardy/vim-slime)
> "Grab some text and send it to a target, most probably: GNU Screen, tmux or Vim Terminal"

Tmux is not the default, to use it you will have to add this line to your .vimrc:

    let g:slime_target = "tmux"

Then add this to configure the sending of commands to a 
[Read Eval Print Loop](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop):
in the general use case of
vim in a split tmux window with a REPL in the other pane:

    let g:slime_default_config = {"socket_name": "default", "target_pane": "{last}"}

Excessive indentation issues can arrise when slime sends indented lines to the
ipython console. For example  after a function definition, such as `def
function_name():` ipython places the cursor at the indented place (4 spaces)
and slime sends an additional 4 (or more spaces) to indent the line further.
This shouldn't be done when slime is sending intput. Ipython's auto indentation
behaviour can be turned off by sending the following command to ipython: 

    %autoindent off


## Syntax highlight

Turn off syntax highlight

    syn off

Start Vim with syntax highlight turned off

    vim -c 'syn off'

You can also specify a rule that vim should turn off syntax highlight for large
files [Stackoverflow question](https://stackoverflow.com/questions/53729940/how-do-i-start-vim-with-syntax-highlighting-off).


### Concealing

#### Markdown

Use the shorthand version `:set cole=0` to turn off concealing of markdown bold
`**` and italic `*` marks as well as the replacement of `# Title` to `§ Title`.
More explanations in [How to prevent vim from hiding symbols in Markdown and
JSON](https://vi.stackexchange.com/questions/7258/how-do-i-prevent-vim-from-hiding-symbols-in-markdown-and-json)

    :set cole=0

Or set the file type to text

    :set ft=text


## Tests

[Vim Test](https://github.com/vim-test/vim-test)
Works with pytest and other testing suites for many languages.
Test results appear in the quick fix window.

[pytest vim](https://github.com/alfredodeza/pytest.vim)
Run pytest from within vim. 


# Terminal interaction

## Bang commands

Use a Bang! to run a command directly, for example to
see how many words are in the file, run:

    :! wc %

To insert the word count directly in the file, run:

    !! wc %

You can copy (`y $`) and paste a command in the vim command line with `CTRL + R + "`.

Insert text from a specified file into the current buffer:

    :r textfile

You can also read in the output of shell applications. For example, if you
wanted to include a list of files from a specific directory, you could include
them using a read command:

    :r ! ls -1 /home/user/directory

Or simply using the double bang

     !! ls

## Shell

[Working with external commands](https://www.linux.com/learn/vim-tips-working-external-commands)
explains how to start a shell:

    :shell

Then exit the shell normally with `exit`.

See also terminal buffer below.

## Terminal buffer

You can start a terminal inside a vim split by entering the command: 

    :terminal

To [enter the normal mode in a terminal buffer](https://vi.stackexchange.com/questions/20643/how-to-enter-normal-mode-while-in-terminal-buffer): 

    CTRL+W+N

Reddit [does anybody use terminal instead of tmux and a normal terminal?](https://www.reddit.com/r/vim/comments/8zlsdo/does_anybody_use_terminal_instead_of_tmux_and_a/)
Some users prefer tmux panes and windows, others prefer vim terminal. 
I have not used vim terminal buffers enough to know how to use them properly. 
For example [slime is also working with vim's terminal](https://vimawesome.com/plugin/vim-slime#vim-terminal)

To start a vertical terminal:

    :vert term

Start a make action: 

    :term make

Start ipython3:

    :vert term ipython3

Change the terminal window size to be 4 lines high (works for all subsequent
opening of a terminal `:term`) 

    :set termwinsize=4x
    :set tws=4x

Change the size of the current terminal

    :res 10


# Tools

## Count words

[Word coung](https://vim.fandom.com/wiki/Word_count):
> To count the number of words in the current buffer, press g then Ctrl-g. To
> count the number of words in a block, select the block (for example, type V5j
> to select 6 lines) or vip to select the current paragraph and again press 

    g
    Ctrl-g


## Macros

Vim wiki [Macros](https://vim.fandom.com/wiki/Macros)

    qn 	start recording to register n
    ... 	your complex series of commands
    q 	stop recording
    @n 	execute your macro
    @@ 	execute your macro again 

> "Suppose you have a macro which operates on the text in a single line. You
> can run the macro on each line in a visual selection in a single operation:
> Visually select some lines (for example, type vip to select the current
> paragraph). Type :normal @q to run the macro from register q on each line."

[Macro to add a new line below each
line](https://stackoverflow.com/a/10414748/2641825)

    qq     " start recording to register q (you could use any register from a to z)
    o      " insert an empty line below cursor
    <Esc>  " switch to normal mode
    jjj    " move the cursor 3 lines downward
    q      " stop recording

Then just move to the start line and type 1000@q to execute your macro 1000 times.


## Spell check

[How to configure vim spellcheck to use two languages](https://superuser.com/questions/911412/how-to-configure-vim-spellcheck-to-use-two-languages)
To use the spellcheck for two languages, add this to your `~/.vimrc`:

    set spell spelllang=en_gb,fr

To use the spellcheck only temporary for an additional language (italian in
this case):

    set spell spelllang=it
    set spell spelllang=de

This might require installing addition Debian packages on the system.

On the first use, vim may give a warning that some word lists are missing. 
[How to make vim download missing word lists](https://www.monolune.com/how-to-make-vim-download-missing-word-lists/)
To solve this issue, turn spell check off

    :set nospell 

Turn spell check on

    :set spell

Then vim will offer to download the missing dictionaries. 

Set spell check only in the local buffer:

    :setlocal spell spelllang=en_gb   

Find alternative for highlighted word:

    z=

[How to make vim spell check remember a word](https://superuser.com/questions/133208/how-to-make-vim-spellcheck-remember-a-new-word)
Mark word as correct, this creates a spell file under /home/user/.vim/spell:

    zg 

Mark word as incorrect

    zw

## Vim diff

View differences between `file1` and `file2` (vim documentation)

    vimdiff file1 file2



# Blogs and resources

This page is the continuation of [my 2014 blog post on Vim commands](https://paulremote.blogspot.de/2014/07/vim-commands.html).


## Other editors

- [Spacemacs](https://www.spacemacs.org/doc/VIMUSERS.html)

    > "Spacemacs is an attempt to improve on both vim and Emacs using the superior
    > modal editing of vim and the nicer configuration language of Emacs."

- [Why atom cant replace vim](https://medium.com/@mkozlows/why-atom-cant-replace-vim-433852f4b4d1)

    > "This philosophy of minimalist commands that can be composed together is the
    > fundamental originating philosophy of Unix, and Vim exemplifies it like no
    > other editor."

- [Jupyter vim](https://github.com/jupyter-vim/jupyter-vim)


## Demonstrations of vim use

Reddit [Python workflow with terminal using
tmux](https://www.reddit.com/r/vim/comments/chdl60/python_workflow_with_terminal_using_tmux/)
I tried slime.

[Browse the web in vim mode](https://github.com/tridactyl/tridactyl)

[Boosting your data science workflow with vim+tmux](https://towardsdatascience.com/boosting-your-data-science-workflow-with-vim-tmux-14505c5e016e)

## Learning vim

* [Should I introduce vim to my kid](https://www.reddit.com/r/vim/comments/aak1lf/should_i_introduce_vim_to_my_kid/)
> "Learn to support, not to shoehorn."

* [Vim adventures](https://vim-adventures.com/)
* [Learn vim basic featurs](https://www.freecodecamp.org/news/learn-linux-vim-basic-features-19134461ab85/)
* [Vim Galore](https://github.com/mhinz/vim-galore#the-vim-philosophy)
  introduction to vim maintained by a group of users


## The history of vim

* [Vim creator Bram Moolenaar
    interview](https://www.binpress.com/vim-creator-bram-moolenaar-interview/)

> "The project I encountered in Kibaale is completely different. The foreigners
> who work there are volunteers, they have sponsors themselves to make it
> possible to live and work there. All the donations for children go to the
> project and are spent there. Also for staff and vehicles, but that’s local
> staff that then spend their money in the country, thus indirectly it helps
> others. And in the end seeing the children grow up, finish their studies and
> find a job is wonderful. "

* [Vi](https://en.wikipedia.org/wiki/Vi)

> "The original code for vi was written by Bill Joy in 1976, as the visual mode
> for a line editor called ex that Joy had written with Chuck Haley.[3] Bill
> Joy's ex 1.1 was released as part of the first Berkeley Software Distribution
> (BSD) Unix release in March 1978. It was not until version 2.0 of ex,
> released as part of Second BSD in May 1979 that the editor was installed
> under the name "vi" (which took users straight into ex's visual mode),[4] and
> the name by which it is known today. 
[...]
On the free software process


* Vim is based on vi, itself based on the [ex
  editor](https://en.wikipedia.org/wiki/Ex_(text_editor))

> "The core ex commands which relate to search and replace are essential to vi.
> For instance, the ex command :%s/XXX/YYY/g replaces every instance of XXX
> with YYY, and works in vi too. The % means every line in the file. The 'g'
> stands for global and means replace every instance on every line (if it was
> not specified, then only the first instance on each line would be replaced).
> "


